[package]
name = "Final_ErrorHandling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.8.1"

[[bin]]
name = "Final_Final_ErrorHandling"
path = "src/lib.rs"